# Generated by Django 2.2.3 on 2019-08-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppermission',
            name='read_only_mode',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
