# Generated by Django 2.2.3 on 2019-08-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_apppermission_read_only_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppermission',
            name='read_only_mode',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
