# Generated by Django 2.2.3 on 2019-08-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSubimission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_file_name', models.FileField(upload_to='')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'file_submission_tbl',
            },
        ),
    ]
