# Generated by Django 2.2.3 on 2019-08-08 17:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_filesubimission_uploaded_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileSubimission',
            new_name='FileSubmission',
        ),
    ]
