# Generated by Django 2.2.3 on 2019-08-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190808_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesubmission',
            name='record_file_name',
            field=models.FileField(upload_to='records/'),
        ),
    ]
