# Generated by Django 2.2.3 on 2019-08-08 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190808_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesubmission',
            name='uploaded_by',
        ),
    ]
