# Generated by Django 2.2.3 on 2019-08-12 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190812_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordsmanagement',
            name='record_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.FileSubmission'),
        ),
    ]
