# Generated by Django 2.2.3 on 2019-08-13 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20190813_0600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='category',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='sub_category',
        ),
    ]
